plugins {
    id 'java'
    id 'net.neoforged.moddev' version "${neoforge_moddev_version}"
}

group = 'com.modernwarfare'
version = '1.0.0'

base {
    archivesName = 'modernwarfare-reforged'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version)
    }

    sourceCompatibility = JavaVersion.toVersion(java_version)
    targetCompatibility = JavaVersion.toVersion(java_version)
    withSourcesJar()
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
        }

        server {
            server()
        }

        data {
            data()
        }
    }

    mods {
        modernwarfare {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = java_version.toInteger()
}

jar {
    manifest {
        attributes(
                'Specification-Title': 'Modern Warfare Reforged',
                'Specification-Vendor': 'modernwarfare',
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': 'modernwarfare'
        )
    }
}
