"""Style preset loading, querying, blending, import, and export."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from ..utils.constants import PRESET_DIR
from ..utils.file_io import read_json, write_json
from ..utils.logger import get_logger
from ..utils.settings import settings_manager
from .preset import StyleParameters, StylePreset

LOGGER = get_logger()


class StyleManager:
    """Repository for built-in and user style presets."""

    def __init__(self) -> None:
        self._presets: dict[str, StylePreset] = {}

    def load_all(self) -> None:
        """Load built-in and user presets."""
        self._presets.clear()
        self._load_from_directory(PRESET_DIR)
        self._load_from_directory(settings_manager.user_preset_dir())
        LOGGER.info("Loaded %d style presets", len(self._presets))

    def _load_from_directory(self, directory: Path) -> None:
        """Load every JSON preset in a directory."""
        if not directory.exists():
            return
        for path in sorted(directory.glob("*.json")):
            try:
                preset = StylePreset.from_dict(read_json(path))
            except RuntimeError as exc:
                LOGGER.warning("Skipping preset %s: %s", path, exc)
                continue
            self._presets[preset.identifier] = preset

    def presets(self) -> list[StylePreset]:
        """Return presets sorted for UI display."""
        return sorted(self._presets.values(), key=lambda item: (item.category, item.display_name))

    def identifiers(self) -> list[str]:
        """Return all preset identifiers."""
        return [preset.identifier for preset in self.presets()]

    def get(self, identifier: str) -> StylePreset:
        """Return a preset by identifier, falling back to the first available preset."""
        if not self._presets:
            self.load_all()
        if identifier in self._presets:
            return self._presets[identifier]
        if self._presets:
            return next(iter(self._presets.values()))
        raise RuntimeError("No style presets are available")

    def enum_items(self) -> list[tuple[str, str, str]]:
        """Return Blender EnumProperty items."""
        if not self._presets:
            self.load_all()
        return [(preset.identifier, preset.display_name, preset.description) for preset in self.presets()]

    def import_preset(self, path: Path) -> StylePreset:
        """Import a preset JSON into the user preset directory."""
        preset = StylePreset.from_dict(read_json(path))
        destination = settings_manager.user_preset_dir() / f"{preset.identifier}.json"
        write_json(destination, preset.to_dict())
        self._presets[preset.identifier] = preset
        return preset

    def export_preset(self, identifier: str, path: Path) -> None:
        """Export a preset by identifier."""
        write_json(path, self.get(identifier).to_dict())

    def add_generated(self, identifier: str, name: str, parameters: StyleParameters) -> StylePreset:
        """Persist an AI-generated preset as a user preset."""
        preset = StylePreset(identifier, name, "AI Generated", "Generated by AI panel", parameters)
        destination = settings_manager.user_preset_dir() / f"{identifier}.json"
        write_json(destination, preset.to_dict())
        self._presets[identifier] = preset
        return preset

    def blend(self, base_id: str, target_id: str, factor: float) -> StylePreset:
        """Create an in-memory blend preset from two existing presets."""
        base = self.get(base_id)
        target = self.get(target_id)
        blended = base.parameters.blended(target.parameters, factor)
        identifier = f"blend_{base.identifier}_{target.identifier}"
        return StylePreset(identifier, f"Blend: {base.display_name} + {target.display_name}", "Blend", "In-memory style blend", blended)


style_manager = StyleManager()
